
services:
  nginx:
    depends_on:
      - php
    build:
      context: docker/nginx
      args:
        SERVER_VERSION: $SERVER_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./sources:$PHP_USER_HOME_DIRECTORY
      - ${EXTERNAL_STORAGE_PATH:-/mnt/betweenus-storage}/uploads:$PHP_USER_HOME_DIRECTORY/uploads
      - ${EXTERNAL_STORAGE_PATH:-/mnt/betweenus-storage}/videos:$PHP_USER_HOME_DIRECTORY/videos
    ports:
      - $SERVER_PORT:80
    restart: unless-stopped

  php:
    depends_on:
      - mariadb
    build:
      context: docker/php
      args:
        PHP_VERSION: $PHP_VERSION
        PHP_USER_NAME: $PHP_USER_NAME
        PHP_USER_IDENTIFIER: $PHP_USER_IDENTIFIER
        PHP_USER_SHELL: $PHP_USER_SHELL
        PHP_USER_HOME_DIRECTORY: $PHP_USER_HOME_DIRECTORY
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: $PHP_USER_HOME_DIRECTORY
    user: php
    volumes:
      - ./sources:$PHP_USER_HOME_DIRECTORY
      - ./migrations:$PHP_USER_HOME_DIRECTORY/migrations
      - ${EXTERNAL_STORAGE_PATH:-/mnt/betweenus-storage}/uploads:$PHP_USER_HOME_DIRECTORY/uploads
      - ${EXTERNAL_STORAGE_PATH:-/mnt/betweenus-storage}/videos:$PHP_USER_HOME_DIRECTORY/videos
    restart: unless-stopped
#    command: ["/usr/local/bin/startup.sh"]

  mariadb:
    build:
      context: docker/mariadb
      args:
        DATABASE_VERSION: $DATABASE_VERSION
    tty: true
    stdin_open: true
    env_file: .env
    working_dir: /var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MARIADB_USER: $DATABASE_USER
      MARIADB_PASSWORD: $DATABASE_PASSWORD
      MARIADB_DATABASE: $DATABASE_NAME
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    depends_on:
      - mariadb
    image: arm64v8/phpmyadmin:latest
    ports:
      - $PHPMYADMIN_PORT:80
    volumes:
      - ./docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.inc.php:ro
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: http://192.168.1.68:8080/
      MYSQL_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
    restart: unless-stopped
